// AnaVectorPilot — proof-of-pipeline: a character generated locally
// (Z-Image-Turbo flat-style sheets), split + vectorized to real SVGs
// (scripts/vector, vtracer), performed as pose-to-pose limited animation
// with the house toon grammar (anticipation, squash, smear, boil).
//
// Deliberately does NOT touch poseCut.tsx: that component is welded to the
// meme_reel pose set and its measured anchors. This one reads the Ana
// anchors fixture (generated by scripts/vector pipeline) and stages beats
// by SHOT SIZE — the s3 drawings are waist-up, so they play as medium
// shots (ground contact pinned below frame) rather than being force-scaled
// to full-body height.
import React from "react";
import {AbsoluteFill, Img, staticFile, useCurrentFrame} from "remotion";
import {actionCurve, bob, boil, holdCurve, smear, squash} from "../motion/toon";
import {Grain, Vignette} from "../motion/Polish";
import anchors from "../fixtures/ana/pose_anchors.json";

type Anchor = {w: number; h: number; ink_h: number; anchor: number[]; src: string};
const A = anchors as unknown as Record<string, Anchor>;

type Beat = {
  at: number;
  pose?: keyof typeof anchors;   // full/medium figure beat...
  head?: string;                 // ...or an expression close-up (svg stem)
  inkH: number;                  // on-screen ink height, px
  footX: number;
  footY: number;                 // ground contact; may sit below frame
  energy?: number;               // smear/squash grade for this cut
  label?: string;
};

const W = 1080;
const H = 1920;
export const ANA_PILOT_FRAMES = 300;

const BEATS: Beat[] = [
  {at: 0,   pose: "front",         inkH: 1050, footX: 540, footY: 1660, energy: 0.9, label: "ANA — drawn by a local model, animated by code"},
  {at: 50,  pose: "point",         inkH: 1500, footX: 470, footY: 2240, energy: 1.1, label: "every pose is a real SVG"},
  {at: 95,  pose: "tablet",        inkH: 1500, footX: 560, footY: 2240, energy: 0.7, label: "vectorized with vtracer — infinitely scalable"},
  {at: 140, head: "s2_06",         inkH: 0, footX: 0, footY: 0, energy: 0.8, label: "expressions"},
  {at: 165, head: "s2_03",         inkH: 0, footX: 0, footY: 0, energy: 1.0, label: "expressions"},
  {at: 190, head: "s2_05",         inkH: 0, footX: 0, footY: 0, energy: 1.2, label: "expressions"},
  {at: 215, pose: "celebrate",     inkH: 1500, footX: 540, footY: 2240, energy: 1.4, label: "cut on the beat, squash on the land"},
  {at: 255, pose: "front",         inkH: 1050, footX: 540, footY: 1660, energy: 0.8, label: "any angle"},
  {at: 270, pose: "three_quarter", inkH: 1050, footX: 540, footY: 1660, energy: 0.6, label: "any angle"},
  {at: 285, pose: "profile",       inkH: 1050, footX: 540, footY: 1660, energy: 0.6, label: "any angle"},
];

const beatAt = (frame: number) => {
  let idx = 0;
  for (let i = 0; i < BEATS.length; i++) if (frame >= BEATS[i].at) idx = i;
  const cur = BEATS[idx];
  const next = BEATS[idx + 1];
  return {cur, since: frame - cur.at, hold: (next ? next.at : ANA_PILOT_FRAMES) - cur.at};
};

const Figure: React.FC<{beat: Beat; since: number; hold: number; frame: number}> = ({
  beat, since, hold, frame,
}) => {
  const a = A[beat.pose as string];
  if (!a) return null;
  const nrg = beat.energy ?? 1;
  const act = actionCurve(since, 3, 6, 9);
  const sq = squash((act - 1) * 0.09 * (0.4 + nrg));
  const sm = smear(since, nrg, 2);
  const d = holdCurve(since, Math.max(1, hold));
  const bl = boil(frame, (beat.pose as string).length, beat.inkH * 0.0014);
  const by = bob(frame, (beat.pose as string).length + 3, beat.inkH * 0.0035, 34);
  const tilt = bob(frame, (beat.pose as string).length, 0.3, 41) + d * 0.4;

  const scale = beat.inkH / a.ink_h;
  const w = a.w * scale;
  const h = a.h * scale;
  const left = beat.footX + bl.x - a.anchor[0] * w;
  const top = beat.footY + by + bl.y - a.anchor[1] * h;
  return (
    <Img
      src={staticFile(a.src)}
      style={{
        position: "absolute", left, top, width: w, height: h,
        transform: `rotate(${tilt}deg) scale(${sq.sx * sm.sx}, ${sq.sy * sm.sy})`,
        transformOrigin: `${a.anchor[0] * 100}% ${a.anchor[1] * 100}%`,
        filter: sm.blur > 0.05 ? `blur(${sm.blur.toFixed(2)}px)` : undefined,
        opacity: sm.opacity,
      }}
    />
  );
};

const HeadPop: React.FC<{beat: Beat; since: number; frame: number}> = ({beat, since, frame}) => {
  const act = actionCurve(since, 2, 5, 8);
  const sq = squash((act - 1) * 0.12);
  const bl = boil(frame, (beat.head as string).length, 1.4);
  const size = 860 * (0.96 + 0.04 * Math.min(1, since / 8));
  return (
    <Img
      src={staticFile(`characters/ana/${beat.head}.svg`)}
      style={{
        position: "absolute",
        left: 540 - size / 2 + bl.x,
        top: 620 - size / 2 + bl.y,
        width: size,
        height: size,
        transform: `scale(${sq.sx}, ${sq.sy})`,
        transformOrigin: "50% 60%",
      }}
    />
  );
};

export const AnaVectorPilot: React.FC = () => {
  const frame = useCurrentFrame();
  const {cur, since, hold} = beatAt(frame);
  const labelPop = actionCurve(since, 2, 4, 8);

  return (
    <AbsoluteFill style={{background: "#0E1526", overflow: "hidden"}}>
      {/* kurzgesagt-ish backdrop: one big flat accent disc, nothing noisy */}
      <div
        style={{
          position: "absolute", left: 540 - 620, top: 900 - 620,
          width: 1240, height: 1240, borderRadius: "50%",
          background: "#16233F",
        }}
      />
      <div
        style={{
          position: "absolute", left: 540 - 480, top: 900 - 480,
          width: 960, height: 960, borderRadius: "50%",
          background: "#1B2C4F",
        }}
      />
      {cur.head ? (
        <HeadPop beat={cur} since={since} frame={frame} />
      ) : (
        <Figure beat={cur} since={since} hold={hold} frame={frame} />
      )}
      {/* beat label — plain type, code-owned, never model-rendered */}
      {cur.label ? (
        <div
          style={{
            position: "absolute", left: 60, right: 60, top: 130,
            textAlign: "center",
            fontFamily: "Arial, sans-serif", fontWeight: 800,
            fontSize: 46, letterSpacing: 1, color: "#E8F0FF",
            transform: `scale(${0.9 + 0.1 * Math.min(1, labelPop)})`,
            opacity: Math.min(1, since / 5),
          }}
        >
          {cur.label}
        </div>
      ) : null}
      <div
        style={{
          position: "absolute", left: 0, right: 0, bottom: 46,
          textAlign: "center", fontFamily: "Arial, sans-serif",
          fontSize: 26, color: "#7E93BD",
        }}
      >
        100% local pipeline — Z-Image-Turbo → vtracer → Remotion · $0/asset
      </div>
      <Vignette strength={0.3} />
      <Grain opacity={0.03} />
    </AbsoluteFill>
  );
};
