"""Assemble the supply-chain chokepoint layer: web/public/data/chokepoints.json
(schema "chokepoints-v1").

NETWORK-FREE. Every field here comes from already-curated/already-retrieved local files:
  chokepoints_source.json             (curated, committed at repo root — see
                                        docs/superpowers/specs/2026-07-15-chokepoints-design.md)
  capital_web.json                    (curated graph, committed at repo root — used only
                                        to cross-validate node_ids, warn-not-fail)
  web/public/data/graph_analysis.json (optional, generated by run_graph_analysis.py —
                                        joined in for graph_crossref; absence degrades
                                        gracefully, is NOT fatal)

source_class="computed" at the top level is deliberate: this feed performs zero new
retrieval, it validates/joins/rolls up an already-curated dataset. Every individual claim
inside `chokepoints` carries its own real source_class (api|html|xhr-json|filing) per
CLAUDE.md rule #3/#5 — provenance lives at the leaf, not just the top.

Hard-fail vs. warn-only (see aiinvest/chokepoints.py docstring for the full rationale):
  - Schema violations (bad enum, missing claim field, dirty sentinel string, duplicate
    id, last_reviewed in the future) ABORT the build (exit 1, nothing written).
  - Unknown node_ids are a WARNING only, collected into
    validation.node_crossref_warnings — a curated entry may reference a node that
    predates the next capital_web.json refresh; that shouldn't brick the whole bundle.

Usage:
    python build_chokepoints.py                      # default paths
    python build_chokepoints.py --out /tmp/cp.json    # debugging
"""
from __future__ import annotations

import argparse
import datetime
import json
import pathlib

from aiinvest import chokepoints as cp

SCHEMA_VERSION = "chokepoints-v1"
SOURCE_CLASS = "computed"
SOURCE_DESC = ("chokepoints_source.json (curated) cross-referenced against "
               "capital_web.json + graph_analysis.json. Claim retrieved_at "
               "stamps mark the curation/search pass, not per-source live "
               "fetches; claims pending live source verification carry "
               "needs_verification=true.")
DISCLAIMER = (
    "Educational research only — not financial advice. Chokepoint severity is "
    "qualitative/indicative, not a probability-weighted loss estimate. Claims with "
    "needs_verification=true are directionally credible, not confirmed. graph_crossref "
    "is a structural (graph-theoretic) signal, distinct from the curated severity_score."
)


def _utc_now():
    return datetime.datetime.now(datetime.timezone.utc)


def _iso(dt):
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _load_json(path):
    p = pathlib.Path(path)
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return None


def _repo_root():
    return pathlib.Path(__file__).resolve().parent.parent


def _default_source_path():
    return str(_repo_root() / "chokepoints_source.json")


def _default_capital_web_path():
    return str(_repo_root() / "capital_web.json")


def _default_graph_analysis_path():
    return str(_repo_root() / "web" / "public" / "data" / "graph_analysis.json")


def _default_out_path():
    return str(_repo_root() / "web" / "public" / "data" / "chokepoints.json")


def build_bundle(args, now=None):
    """Pure-ish assembly (reads local files, no network).

    Returns (bundle_dict_or_None, hard_fail_issues). If hard_fail_issues is non-empty,
    bundle is None and nothing should be written.
    """
    now = now or _utc_now()

    source_doc = _load_json(args.source)
    if source_doc is None:
        return None, [f"source file not found or not valid JSON: {args.source}"]

    issues = cp.validate_dataset(source_doc, now=now)
    if issues:
        return None, issues

    capital_web_doc = _load_json(args.capital_web)
    valid_node_ids = cp.build_node_id_set(capital_web_doc)

    graph_doc = _load_json(args.graph_analysis)
    graph_lookup = cp.build_graph_lookup(graph_doc)

    entries, node_warnings = cp.build_entries(source_doc, valid_node_ids, graph_lookup)
    summary = cp.compute_summary(entries, valid_node_ids)

    bundle = {
        "schema_version": SCHEMA_VERSION,
        "generated_at": _iso(now),
        "source_class": SOURCE_CLASS,
        "source": SOURCE_DESC,
        "disclaimer": DISCLAIMER,
        "validation": {"node_crossref_warnings": node_warnings, "schema_ok": True},
        "summary": summary,
        "chokepoints": entries,
    }
    return bundle, []


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Assemble chokepoints.json from chokepoints_source.json "
                    "(no network — pure validate/join/rollup of curated data).")
    ap.add_argument("--source", default=_default_source_path(),
                    help="Curated input (default: <repo_root>/chokepoints_source.json).")
    ap.add_argument("--capital-web", default=_default_capital_web_path(),
                    help="Curated graph, used to cross-validate node_ids "
                         "(default: <repo_root>/capital_web.json).")
    ap.add_argument("--graph-analysis", default=_default_graph_analysis_path(),
                    help="Optional; joined in for graph_crossref "
                         "(default: web/public/data/graph_analysis.json). Absence is "
                         "not fatal — graph_crossref degrades gracefully.")
    ap.add_argument("--out", default=_default_out_path(),
                    help="Output path (default: web/public/data/chokepoints.json).")
    args = ap.parse_args(argv)

    bundle, issues = build_bundle(args)

    if issues:
        print(f"chokepoints: {len(issues)} schema validation issue(s) — aborting, "
              f"nothing written:")
        for issue in issues[:50]:
            print(f"  FAIL  {issue}")
        if len(issues) > 50:
            print(f"  ... and {len(issues) - 50} more")
        return 1

    for w in bundle["validation"]["node_crossref_warnings"]:
        print(f"  WARN  {w}")

    out_path = pathlib.Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(bundle, indent=2), encoding="utf-8")

    s = bundle["summary"]
    print(f"chokepoints: {s['n_entries']} entries, {s['n_claims']} claims "
          f"(fact={s['n_fact']} reported={s['n_reported']} rumored={s['n_rumored']}) "
          f"-> {out_path}")
    print(f"  needs_verification: {s['n_needs_verification']}  "
          f"node_ids resolved: {s['n_node_ids_resolved']}/{s['n_node_ids_total']}")
    print(f"  node_crossref_warnings: {len(bundle['validation']['node_crossref_warnings'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
